### ISSUE TITLE
java.lang.NoSuchMethodError: org.quartz.SchedulerMetaData.getRunningSince()Ljava/util/Date on dashboard

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mike10004/myschedule#101]
```
Hi Team,

I have downloaded myscheduler 1.6.0. I am working on spring 3.0.5 and quartz 
1.8.6. I want to integrate with myscheduler UI.

I am using Jboss as server , I had deployed your war into /deploy directory. 
When I started the server, and click on DashBoard, I am getting below error.

Please help me if I am doing anything wrong. It is a kind a urgent project for 
me.

An application error has occurred during your request. Please report this to 
the administrator.

Status Code: 500

Message: Servlet execution threw an exception

Error Type: class java.lang.NoSuchMethodError

Show more details

java.lang.NoSuchMethodError: 
org.quartz.SchedulerMetaData.getRunningSince()Ljava/util/Date;
    at myschedule.web.servlet.app.handler.DashboardHandlers$2.handleViewData(DashboardHandlers.java:80)
    at myschedule.web.servlet.UrlRequestActionHandler.handleAction(UrlRequestActionHandler.java:49)
    at myschedule.web.servlet.ActionHandlerServlet.process(ActionHandlerServlet.java:104)
    at myschedule.web.servlet.AbstractControllerServlet.doGet(AbstractControllerServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
    at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
    at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
    at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:598)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
    at java.lang.Thread.run(Thread.java:662)
```

Original issue reported on code.google.com by `rohini.n...@gmail.com` on 22 Oct 2012 at 10:31
